# Generated by Django 2.2.3 on 2020-12-04 07:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Modes of acquisition',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForceStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Fssu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=32, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'FSSU',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('fullname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'PAMU',
            },
        ),
        migrations.CreateModel(
            name='ProcurementMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Mode of procurement',
                'verbose_name_plural': 'Modes of procurement',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=128)),
                ('island_group', models.CharField(choices=[('Luzon', 'Luzon'), ('Visayas', 'Visayas'), ('Mindanao', 'Mindanao')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Serviceability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Serviceabilities',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('alt_pamu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alt_sub_units', to='commons.Pamu')),
                ('mother_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commons.Pamu')),
                ('pamu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_units', to='commons.Pamu')),
            ],
        ),
        migrations.CreateModel(
            name='Sprs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pamu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.Pamu')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='commons.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=12, null=True)),
                ('initials', models.CharField(default='', max_length=8)),
                ('active', models.BooleanField(default=False)),
                ('require_change_pw', models.BooleanField(default=True)),
                ('bypass_otp', models.BooleanField(default=False)),
                ('special_permissions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fssu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons.Fssu')),
                ('pamu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons.Pamu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='commons.Role')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
