# Generated by Django 2.2.3 on 2020-12-08 05:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceDirective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('series', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('unit', models.CharField(default='pc', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Item')),
            ],
        ),
        migrations.CreateModel(
            name='NomenclatureIcie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pamu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Pamu')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Nomenclature')),
                ('unit_recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_ins', to='tosb.Unit')),
                ('unit_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_outs', to='tosb.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='TOSPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(blank=True, choices=[('OE', 'OE'), ('ICIE', 'ICIE'), ('POL', 'POL')], max_length=8, null=True)),
                ('branch', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('year', models.IntegerField()),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('action', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOS Policies',
                'verbose_name_plural': 'TOS Policies',
            },
        ),
        migrations.CreateModel(
            name='Toe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toe', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='RMCRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_year', models.IntegerField()),
                ('project_type', models.CharField(blank=True, choices=[('Repair of Existing POL Dump', 'Repair of Existing POL Dump'), ('Construction of New POL Dump', 'Construction of New POL Dump'), ('Procurement of POL-related Equipment', 'Procurement of POL-related Equipment'), ('Others', 'Others')], max_length=100, null=True)),
                ('project_name', models.CharField(max_length=512)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('unit', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('remarks', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RMC',
                'verbose_name_plural': 'RMC',
            },
        ),
        migrations.CreateModel(
            name='OutgoingCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commo_type', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('control_number', models.CharField(max_length=512)),
                ('origin_branch_office_unit', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('recepient_unit', models.CharField(max_length=512)),
                ('date_received', models.DateTimeField()),
                ('remarks', models.CharField(max_length=512)),
                ('received_by', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outgoing Communication',
                'verbose_name_plural': 'Outgoing Communication',
            },
        ),
        migrations.CreateModel(
            name='OEStockStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li', models.CharField(max_length=512)),
                ('nomenclature', models.CharField(max_length=512)),
                ('price', models.FloatField()),
                ('beg_balance', models.FloatField()),
                ('receipt', models.CharField(max_length=512)),
                ('issuance', models.CharField(max_length=512)),
                ('auth_id_number', models.CharField(max_length=512)),
                ('date_accepted_issued', models.DateField()),
                ('date_expiration', models.DateField()),
                ('end_balance', models.FloatField()),
                ('end_user', models.CharField(max_length=512)),
                ('supplier_remarks', models.TextField()),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OE Stock Status',
                'verbose_name_plural': 'OE Stock Status',
            },
        ),
        migrations.CreateModel(
            name='OERecap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=512)),
                ('on_hand', models.FloatField()),
                ('balance', models.FloatField()),
                ('ats', models.CharField(max_length=512)),
                ('unit', models.CharField(max_length=512)),
                ('fill_up_rate', models.FloatField()),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OE Recap',
                'verbose_name_plural': 'OE Recap',
            },
        ),
        migrations.CreateModel(
            name='OEProgramming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=512)),
                ('on_hand', models.FloatField()),
                ('balance', models.FloatField()),
                ('ats', models.CharField(max_length=512)),
                ('unit', models.CharField(max_length=512)),
                ('fill_up_rate', models.FloatField()),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OE Programming',
                'verbose_name_plural': 'OE Programming',
            },
        ),
        migrations.CreateModel(
            name='OEMasterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=512)),
                ('ats', models.CharField(max_length=512)),
                ('unit', models.CharField(max_length=512)),
                ('total_price', models.FloatField()),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OE Masterlist',
                'verbose_name_plural': 'OE Masterlist',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Type'),
        ),
        migrations.CreateModel(
            name='IssuanceDirectiveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('issuance_directive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.IssuanceDirective')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Nomenclature')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_branch', models.CharField(max_length=512)),
                ('commo_type', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('control_number', models.CharField(max_length=512)),
                ('date_received', models.DateTimeField()),
                ('unit_office', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('remarks', models.CharField(max_length=512)),
                ('received_by', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Communication',
                'verbose_name_plural': 'Incoming Communication',
            },
        ),
        migrations.CreateModel(
            name='ICIERecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_year', models.IntegerField()),
                ('list_of_specification_in_out', models.CharField(blank=True, choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=50, null=True)),
                ('list_of_specification_source', models.CharField(blank=True, choices=[('AFP', 'AFP'), ('PA', 'PA')], max_length=8, null=True)),
                ('project_name', models.CharField(max_length=512)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('unit', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=512)),
                ('remarks', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/tosb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ICIE',
                'verbose_name_plural': 'ICIE',
            },
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('baseline', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Ats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('ats', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tosb.Unit')),
            ],
        ),
    ]
