# Generated by Django 2.2.3 on 2020-12-04 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PAProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_source', models.CharField(blank=True, choices=[('Capital Outlay', 'Capital Outlay'), ('MOOE', 'MOOE'), ('PS', 'PS'), ('Others', 'Others')], max_length=50, null=True)),
                ('year', models.IntegerField()),
                ('type_of_commodity', models.CharField(max_length=512)),
                ('project_title', models.CharField(max_length=512)),
                ('unit_procurement_request_number', models.CharField(max_length=512)),
                ('solicitation_number', models.CharField(max_length=512)),
                ('mode_of_procurement', models.CharField(max_length=512)),
                ('approved_budget_contract', models.FloatField()),
                ('supplier', models.CharField(max_length=512)),
                ('bid_amount', models.FloatField()),
                ('current_status', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=utils.PathAndRename('uploads/samb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PA Project',
            },
        ),
        migrations.CreateModel(
            name='PITCProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_source', models.CharField(blank=True, choices=[('Capital Outlay', 'Capital Outlay'), ('MOOE', 'MOOE'), ('PS', 'PS'), ('Others', 'Others')], max_length=50, null=True)),
                ('year', models.IntegerField()),
                ('type_of_commodity', models.CharField(max_length=512)),
                ('project_title', models.CharField(max_length=512)),
                ('unit_procurement_request_number', models.CharField(max_length=512)),
                ('solicitation_number', models.CharField(max_length=512)),
                ('mode_of_procurement', models.CharField(max_length=512)),
                ('approved_budget_contract', models.FloatField()),
                ('supplier', models.CharField(max_length=512)),
                ('bid_amount', models.FloatField()),
                ('current_status', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=utils.PathAndRename('uploads/samb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PITC Project',
            },
        ),
        migrations.CreateModel(
            name='TWGRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=512)),
                ('bac_designation', models.CharField(max_length=512)),
                ('unit_description', models.CharField(max_length=512)),
                ('contact_number', models.CharField(max_length=512)),
                ('remarks', models.TextField()),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=utils.PathAndRename('uploads/samb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technical Working Group',
                'verbose_name_plural': 'Technical Working Group',
            },
        ),
        migrations.CreateModel(
            name='ProcurementActivityPITCProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=512)),
                ('details', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pitc_project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_activity', to='samb.PITCProject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementActivityPAProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=512)),
                ('details', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pa_project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_activity', to='samb.PAProject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commo_type', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('control_number', models.CharField(max_length=512)),
                ('origin_branch_office_unit', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('recepient_unit', models.CharField(max_length=512)),
                ('date_received', models.DateTimeField()),
                ('remarks', models.CharField(max_length=512)),
                ('received_by', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=utils.PathAndRename('uploads/samb/%Y/%m/'))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outgoing Communication',
            },
        ),
        migrations.CreateModel(
            name='IncomingCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_branch', models.CharField(max_length=512)),
                ('commo_type', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('control_number', models.CharField(max_length=512)),
                ('date_received', models.DateTimeField()),
                ('unit_office', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('remarks', models.CharField(max_length=512)),
                ('received_by', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=utils.PathAndRename('uploads/samb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Communication',
            },
        ),
        migrations.CreateModel(
            name='BACRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=512)),
                ('bac_designation', models.CharField(max_length=512)),
                ('unit_description', models.CharField(max_length=512)),
                ('contact_number', models.CharField(max_length=512)),
                ('remarks', models.TextField()),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=utils.PathAndRename('uploads/samb/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bids And Awards Committee',
                'verbose_name_plural': 'Bids And Awards Committee',
            },
        ),
    ]
