# Generated by Django 2.2.3 on 2021-09-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20201208_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavyequipment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
