Mode_OF_ACQUISITION=(
    ("PFIS","PFIS"),
    ("Regular Agency Fund","Regular Agency Fund"),
    ("BCDA Fund","BCDA Fund"),
    ("Modernization Fund","Modernization Fund"),
    ("PA Modernization Fund","PA Modernization Fund")
)

Facility_Classification = (
    ("Admin Building","Admin Building"),
    ("Apartment","Apartment"),
    ("Armory","Armory"),
    ("Barracks","Barracks"),
    ("Base Utilities","Base Utilities"),
    ("Base Utilities and Facility","Base Utilities and Facility"),
    ("Building","Building"),
    ("Bleacher","Bleacher"),
    ("Chapel","Chapel"),
    ("Classroom","Classroom"),
    ("Clubhouse","Clubhouse"),
    ("Community Facilities","Community Facilities"),
    ("Conference Room","Conference Room"),
    ("Covered Court","Covered Court"),
    ("CR","CR"),
    ("Dispensary","Dispensary"),
    ("Dump","Dump"),
    ("Garage","Garage"),
    ("Grandstand","Grandstand"),
    ("Gym","Gym"),
    ("Hall","Hall"),
    ("Maintenance Facilities","Maintenance Facilities"),
    ("Mess Hall","Mess Hall"),
    ("Museum","Museum"),
    ("Office","Office"),
    ("Operational Facilities","Operational Facilities"),
    ("Operational Support Facilities","Operational Support Facilities"),
    ("Post","Post"),
    ("Power House","Power House"),
    ("Pump House","Pump House"),
    ("Quarters","Quarters"),
    ("School","School"),
    ("Social Hall","Social Hall"),
    ("Stockage","Stockage"),
    ("Trancient","Trancient"),
    ("Warehouse","Warehouse")
)

PAMU_LIST=(
    ('1ID','1ID'),
    ('2ID','2ID'),
    ('3ID','3ID'),
    ('4ID','4ID'),
    ('5ID','5ID'),
    ('6ID','6ID'),
    ('7ID','7ID'),
    ('8ID','8ID'),
    ('9ID','9ID'),
    ('10ID','10ID'),
    ('11ID','11ID'),
    ('1BCT','1BCT'),
    ('51EBde','51EBde'),
    ('52EBde','52EBde'),
    ('53EBde','53EBde'),
    ('54EBde','54EBde'),
    ('55EBde','55EBde'),
    ('AAR','AAR'),
    ('AFPPS','AFPPS'),
    ('AIR','AIR'),
    ('APAO','APAO'),
    ('APMC','APMC'),
    ('ARESCOM','ARESCOM'),
    ('ARMOR','ARMOR'),
    ('ASCOM','ASCOM'),
    ('ASPA','ASPA'),
    ('ASR','ASR'),
    ('AVnR','AVnR'),
    ('CMOR','CMOR'),
    ('FCPA','FCPA'),
    ('FSRR','FSRR'),
    ('HHSG','HHSG'),
    ('IMCOM','IMCOM'),
    ('LRR','LRR'),
    ('SFR (A)','SFR (A)'),
    ('SOCOM','SOCOM'),
    ('TRADOC','TRADOC')
)

SUB_UNIT_LIST = (
    ("1002IBde","1002IBde"),
    ("101Bde","101Bde"),
    ("102BDE","102BDE"),
    ("103 Brigade","103 Brigade"),
    ("107TH CO","107TH CO"),
    ("109th CO","109th CO"),
    ("10DTS","10DTS"),
    ("10FAU","10FAU"),
    ("10FPAO","10FPAO"),
    ("10FSFO","10FSFO"),
    ("10FSSU","10FSSU"),
    ("10IB","10IB"),
    ("10IMB","10IMB"),
    ("10ISU","10ISU"),
    ("10RCDG","10RCDG"),
    ("1101BDE","1101BDE"),
    ("111CO","111CO"),
    ("112CO","112CO"),
    ("11DTS","11DTS"),
    ("11FPAO","11FPAO"),
    ("11FSSU","11FSSU"),
    ("11ISU","11ISU"),
    ("11RCDG","11RCDG"),
    ("11SIGBN","11SIGBN"),
    ("11SSBn","11SSBn"),
    ("12FSFO","12FSFO"),
    ("12FSSU","12FSSU"),
    ("12ISU","12ISU"),
    ("1301DD","1301DD"),
    ("14AIB","14AIB"),
    ("14FSFO","14FSFO"),
    ("14RCDG","14RCDG"),
    ("15AIB","15AIB"),
    ("15FPAO","15FPAO"),
    ("15FSFO","15FSFO"),
    ("16FPAO","16FPAO"),
    ("16ISU","16ISU"),
    ("17AIB","17AIB"),
    ("17FAU","17FAU"),
    ("17FPAO","17FPAO"),
    ("17FSFO","17FSFO"),
    ("17IB","17IB"),
    ("18IB","18IB"),
    ("191MPBn","191MPBn"),
    ("1ATG","1ATG"),
    ("1Cav Co(S)","1Cav Co(S)"),
    ("1CMOBn","1CMOBn"),
    ("1FSSU","1FSSU"),
    ("1ID","1ID"),
    ("1IMB","1IMB"),
    ("1ISU","1ISU"),
    ("1LSG","1LSG"),
    ("1MBN","1MBN"),
    ("1MIB","1MIB"),
    ("1RCDG","1RCDG"),
    ("1SBn","1SBn"),
    ("1SRB","1SRB"),
    ("1SSBN","1SSBN"),
    ("201BDE","201BDE"),
    ("202Bde","202Bde"),
    ("202IBde","202IBde"),
    ("203BDE","203BDE"),
    ("20IB","20IB"),
    ("21CAV COy","21CAV COy"),
    ("21SRC","21SRC"),
    ("22CAV Coy","22CAV Coy"),
    ("23CAV Coy","23CAV Coy"),
    ("24ISU","24ISU"),
    ("2ASH","2ASH"),
    ("2CAV","2CAV"),
    ("2CAVCoy","2CAVCoy"),
    ("2DCAU","2DCAU"),
    ("2DTS","2DTS"),
    ("2FSFO","2FSFO"),
    ("2FSSU","2FSSU"),
    ("2IMB","2IMB"),
    ("2ISU","2ISU"),
    ("2LSG","2LSG"),
    ("2Mech Bde","2Mech Bde"),
    ("2SFBN","2SFBN"),
    ("2SRB","2SRB"),
    ("2SRC","2SRC"),
    ("2SSBn","2SSBn"),
    ("301BDE","301BDE"),
    ("302BDE","302BDE"),
    ("303BDE","303BDE"),
    ("32IB","32IB"),
    ("33IB","33IB"),
    ("38IB","38IB"),
    ("3cavcoy","3cavcoy"),
    ("3FAB","3FAB"),
    ("3FSFO","3FSFO"),
    ("3ISU","3ISU"),
    ("3Mech Bn","3Mech Bn"),
    ("3RCDG","3RCDG"),
    ("3SigBn","3SigBn"),
    ("3SRB","3SRB"),
    ("407CDC","407CDC"),
    ("40IB","40IB"),
    ("41IB","41IB"),
    ("45IB","45IB"),
    ("46IB","46IB"),
    ("4CAVCoy","4CAVCoy"),
    ("4DTS","4DTS"),
    ("4FAB","4FAB"),
    ("4FPAO","4FPAO"),
    ("4FSFO","4FSFO"),
    ("4FSSU","4FSSU"),
    ("4ISU","4ISU"),
    ("4RCDG","4RCDG"),
    ("4SRB","4SRB"),
    ("500ECB","500ECB"),
    ("501BDE","501BDE"),
    ("503BDE","503BDE"),
    ("512ECB","512ECB"),
    ("513ECB","513ECB"),
    ("514ECB","514ECB"),
    ("51ESB","51ESB"),
    ("51ESC","51ESC"),
    ("522ECB","522ECB"),
    ("524ECB","524ECB"),
    ("525ECB","525ECB"),
    ("534ECB","534ECB"),
    ("542ECB","542ECB"),
    ("543ECB","543ECB"),
    ("544ECB","544ECB"),
    ("545ECB","545ECB"),
    ("546ECB","546ECB"),
    ("547ECB","547ECB"),
    ("548ECB","548ECB"),
    ("549ECB","549ECB"),
    ("551ECB","551ECB"),
    ("552ECB","552ECB"),
    ("564ECB","564ECB"),
    ("565ECB","565ECB"),
    ("5DCAU/ 77IB","5DCAU/ 77IB"),
    ("5DTS","5DTS"),
    ("5FAB","5FAB"),
    ("5FSFO","5FSFO"),
    ("5FSSU","5FSSU"),
    ("5IMB","5IMB"),
    ("5ISU","5ISU"),
    ("5RCDG","5RCDG"),
    ("5SRB","5SRB"),
    ("601BDE","601BDE"),
    ("602BDE","602BDE"),
    ("6CAV Coy","6CAV Coy"),
    ("6DCAU","6DCAU"),
    ("6FAB","6FAB"),
    ("6FAU","6FAU"),
    ("6FMSC","6FMSC"),
    ("6FSFO","6FSFO"),
    ("6FSSU","6FSSU"),
    ("6RCDG","6RCDG"),
    ("6SBn","6SBn"),
    ("701B","701B"),
    ("701BDE","701BDE"),
    ("702Bde","702Bde"),
    ("702CDC","702CDC"),
    ("703BDE","703BDE"),
    ("703CDC","703CDC"),
    ("704CDC","704CDC"),
    ("72IB","72IB"),
    ("77IB","77IB"),
    ("78IB","78IB"),
    ("7DTS","7DTS"),
    ("7FSFO","7FSFO"),
    ("7FSSU","7FSSU"),
    ("7IMB","7IMB"),
    ("7RCDG","7RCDG"),
    ("801BDE","801BDE"),
    ("802BDE","802BDE"),
    ("802CDC","802CDC"),
    ("803BDE","803BDE"),
    ("806CDC","806CDC"),
    ("84IB","84IB"),
    ("86IB","86IB"),
    ("88IB","88IB"),
    ("8FSSU","8FSSU"),
    ("8ISU","8ISU"),
    ("8MIB","8MIB"),
    ("8RCDG","8RCDG"),
    ("901st Bde","901st Bde"),
    ("902BDE","902BDE"),
    ("903BDE","903BDE"),
    ("91IB","91IB"),
    ("95IB","95IB"),
    ("98IB","98IB"),
    ("9CMOBn","9CMOBn"),
    ("9DTS","9DTS"),
    ("9FAB","9FAB"),
    ("9FSFO","9FSFO"),
    ("9FSSU","9FSSU"),
    ("9IMB","9IMB"),
    ("9ISU","9ISU"),
    ("9PED","9PED"),
    ("9RCDG","9RCDG"),
    ("9SSBN","9SSBN"),
    ("AABn","AABn"),
    ("AFPCGSC","AFPCGSC"),
    ("AFPPS","AFPPS"),
    ("AGH","AGH"),
    ("AGSMO","AGSMO"),
    ("AHO","AHO"),
    ("AHRO","AHRO"),
    ("AIR","AIR"),
    ("AMC","AMC"),
    ("APMC","APMC"),
    ("AREC","AREC"),
    ("ARO-M","ARO-M"),
    ("ASM","ASM"),
    ("ATS","ATS"),
    ("C2C","C2C"),
    ("C2C (P)","C2C (P)"),
    ("CAC","CAC"),
    ("CB","CB"),
    ("CC (P)","CC (P)"),
    ("CEASH","CEASH"),
    ("CLSH","CLSH"),
    ("CMOBN","CMOBN"),
    ("CMOR","CMOR"),
    ("CMOS","CMOS"),
    ("CSSH","CSSH"),
    ("DSM","DSM"),
    ("EODBN","EODBN"),
    ("ESBN","ESBN"),
    ("ESC","ESC"),
    ("FBHFMC","FBHFMC"),
    ("FC","FC"),
    ("FCPA","FCPA"),
    ("G3","G3"),
    ("G7","G7"),
    ("GSMO","GSMO"),
    ("H10ID","H10ID"),
    ("H11ID","H11ID"),
    ("H1LSG","H1LSG"),
    ("H1ID","H1ID"),
    ("H1SBN","H1SBN"),
    ("H2ID","H2ID"),
    ("H3ID","H3ID"),
    ("H4ID","H4ID"),
    ("H3ID","H3ID"),
    ("H4ID","H4ID"),
    ("H52E","H52E"),
    ("H54E","H54E"),
    ("H55E","H55E"),
    ("H5ID","H5ID"),
    ("H6ID","H6ID"),
    ("H7ID","H7ID"),
    ("H7RCDG","H7RCDG"),
    ("H8ID","H8ID"),
    ("H9ID","H9ID"),
    ("HAAR","HAAR"),
    ("HASPA","HASPA"),                                 
    ("HFSRR","HFSRR"),                                 
    ("HHSBn","HHSBn"),                                 
    ("HHSG","HHSG"),                                
    ("HLRR","HLRR"),                                 
    ("HQS","HQS"),                                 
    ("HSBn","HSBn"),                                 
    ("HSFRA","HSFRA"),                                 
    ("IMTC","IMTC"),                                 
    ("K9BN","K9BN"),                                 
    ("LETB","LETB"),                                 
    ("LRS","LRS"),                                 
    ("MATG","MATG"),                                 
    ("LRS","LRS"),                                 
    ("MATG","MATG"),                                 
    ("MFO","MFO"),                                 
    ("MPBn","MPBn"),                                 
    ("MTC (P)","MTC (P)"),                                 
    ("NCRRCDG","NCRRCDG"),                                 
    ("NETBn","NETBn"),                                 
    ("OAA","OAA"),                                 
    ("OACE","OACE"),                                 
    ("OACESPA","OACESPA"),                                 
    ("OACH","OACH"),                                 
    ("OACOCS","OACOCS"),                                 
    ("OACPA","OACPA"),                                 
    ("OAGAD","OAGAD"),                                 
    ("OAIA","OAIA"),                                 
    ("OAJA","OAJA"),                                 
    ("OAPM","OAPM"),                                 
    ("OCDS","OCDS"),                                 
    ("OCG","OCG"),                                 
    ("OG1","OG1"),                                 
    ("OG10","OG10"),                                
    ("OG3","OG3"),                                 
    ("OG5,PA","OG5),PA"),                                 
    ("OG7","OG7"),                                 
    ("OG7/OG8","OG7/OG8"),                                 
    ("OG7","OG7"),                                 
    ("OG7/OG8","OG7/OG8"),                                 
    ("OG9","OG9"),                                 
    ("OPCC","OPCC"),                                 
    ("OVC","OVC"),                                 
    ("PABAC","PABAC"),                                 
    ("PAICoe","PAICoe"),                                 
    ("PAOLCI","PAOLCI"),                                 
    ("PAPC","PAPC"),                                 
    ("PED","PED"),                                 
    ("PED,HHSBn","PED,HHSBn"),                                 
    ("PGAB","PGAB"),                                 
    ("PMO","PMO"),                                 
    ("PSD","PSD"),                                 
    ("RAD","RAD"),                                 
    ("RDC","RDC"),                                 
    ("REPEWC","REPEWC"),                                 
    ("SC (P)","SC (P)"),                                 
    ("SCS","SCS"),                                 
    ("SEBN","SEBN"),                                 
    ("SFS","SFS"),                                 
    ("SMAC","SMAC"),                                 
    ("SOCOM","SOCOM"),                                 
    ("SRC","SRC"),                                 
    ("SRS","SRS"),                                 
    ("SRC","SRC"),                                 
    ("SRS","SRS"),                                 
    ("SRTS","SRTS"),                                 
    ("SSBN","SSBN"),                                 
    ("SSC","SSC"),                                 
    ("SSTS","SSTS"),                                 
    ("SWMO","SWMO"),                                 
    ("TAP","TAP"),                                 
    ("TF Gensan","TF Gensan"),                                 
    ("TSS","TSS"),                                 
    ("TSSC (P)","TSSC (P)"),                                 
    ("UPO","UPO"),                                 
    ("VATG","VATG")
)