# Generated by Django 2.2.3 on 2021-09-07 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomplishmentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pamu', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('quarter', models.CharField(blank=True, choices=[('1st', 'First Quarter'), ('2nd', 'Second Quarter'), ('3rd', 'Third Quarter'), ('4th', 'Fourth Quarter')], max_length=100, null=True)),
                ('month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100, null=True)),
                ('date_received', models.DateField()),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/lob/%Y/%m/'))),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accomplishment Report',
                'verbose_name_plural': 'Accomplishment Reports',
            },
        ),
        migrations.CreateModel(
            name='StatusAccomplishmentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('control_number', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('origin_office_unit', models.CharField(max_length=512)),
                ('out_for_action_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('in_with_action', models.CharField(blank=True, max_length=512, null=True)),
                ('out_for_approval', models.CharField(blank=True, max_length=512, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/lob/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accomplishment_report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_accomplishment_reports', to='lob.AccomplishmentReport')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status/Accomplishment Reports',
                'verbose_name_plural': 'Status/Accomplishment Reports',
            },
        ),
        migrations.CreateModel(
            name='PCHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_status', models.CharField(blank=True, choices=[('Programmed', 'Programmed'), ('Unprogrammed', 'Unprogrammed')], max_length=50, null=True)),
                ('number', models.CharField(max_length=512)),
                ('unit', models.CharField(max_length=512)),
                ('purpose', models.TextField()),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/lob/%Y/%m/'))),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PCHT',
            },
        ),
        migrations.CreateModel(
            name='OutgoingCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commo_type', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('control_number', models.CharField(max_length=512)),
                ('origin_branch_office_unit', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('recepient_unit', models.CharField(max_length=512)),
                ('date_received', models.DateTimeField()),
                ('remarks', models.CharField(max_length=512)),
                ('received_by', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/lob/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outgoing Communication',
            },
        ),
        migrations.CreateModel(
            name='LogisticsSupportPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(blank=True, choices=[('Activations', 'Activations'), ('Operationalization', 'Operationalization'), ('Regularization', 'Regularization')], max_length=50, null=True)),
                ('number', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/lob/%Y/%m/'))),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistics Support Plan',
            },
        ),
        migrations.CreateModel(
            name='IssuesAndConcerns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pamu', models.CharField(max_length=512)),
                ('sub_unit', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('concerned_branch', models.CharField(max_length=512)),
                ('issues_and_concerns', models.TextField()),
                ('action_taken', models.TextField()),
                ('remarks', models.TextField()),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/lob/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issues and Concerns',
                'verbose_name_plural': 'Issues and Concerns',
            },
        ),
        migrations.CreateModel(
            name='IncomingCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_branch', models.CharField(max_length=512)),
                ('commo_type', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('control_number', models.CharField(max_length=512)),
                ('date_received', models.DateTimeField()),
                ('unit_office', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('remarks', models.CharField(max_length=512)),
                ('received_by', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/lob/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Communication',
            },
        ),
        migrations.CreateModel(
            name='CommandDirectedActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('status', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/lob/%Y/%m/'))),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Command Directed Activities (CAD)',
                'verbose_name_plural': 'Command Directed Activities (CAD)',
            },
        ),
    ]
