# Generated by Django 2.2.3 on 2020-12-08 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0002_auto_20201208_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('transport_type', models.CharField(choices=[('GMA', 'Ground Mobility'), ('SMA', 'Sea Mobility'), ('AMA', 'Air Mobility')], max_length=8)),
                ('prefix', models.CharField(max_length=4)),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NomenclatureTire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NomenclatureVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('nomenclature', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tonnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Tonnage',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=512)),
                ('item_code', models.CharField(blank=True, max_length=16, null=True)),
                ('plate_no', models.CharField(blank=True, max_length=64, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=128, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=32, null=True)),
                ('mvf', models.CharField(blank=True, max_length=32, null=True)),
                ('conduction_no', models.CharField(blank=True, max_length=64, null=True)),
                ('acquisition_year', models.PositiveIntegerField(blank=True, null=True)),
                ('geographical_location', models.CharField(blank=True, choices=[('Luzon', 'Luzon'), ('Visayas', 'Visayas'), ('Mindanao', 'Mindanao')], max_length=32, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('has_bfp', models.BooleanField(default=False)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquisition_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_records', to='commons.AcquisitionMode')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_records', to='mobility.NomenclatureVehicle')),
                ('serviceability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_records', to='commons.Serviceability')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commons.Unit')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('serial', 'nomenclature')},
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('prefix', models.CharField(max_length=4)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='mobility.Category')),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='mobility.Type')),
            ],
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateField()),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('implementation', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major')], max_length=8)),
                ('authority', models.CharField(blank=True, max_length=32, null=True)),
                ('advice_no', models.CharField(blank=True, max_length=32, null=True)),
                ('period_covered', models.CharField(blank=True, choices=[('Q1', '1st Qtr'), ('Q2', '2nd Qtr'), ('Q3', '3rd Qtr'), ('Q4', '4th Qtr')], max_length=8, null=True)),
                ('amount_released', models.FloatField()),
                ('has_fur', models.BooleanField(default=False)),
                ('asa_number', models.CharField(max_length=512)),
                ('current_market_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commons.Unit')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repair_records', to='mobility.VehicleRecord')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(max_length=150)),
                ('plate_number', models.CharField(max_length=32)),
                ('plate_number_type', models.CharField(max_length=32)),
                ('mv_file', models.FileField(upload_to=utils.PathAndRename('uploads/mobility/%Y/%m/'))),
                ('registration_date', models.DateField()),
                ('action', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commons.Unit')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mobility.VehicleRecord')),
            ],
            options={
                'verbose_name': 'Registration Records',
                'verbose_name_plural': 'Registration Records',
            },
        ),
        migrations.AddField(
            model_name='nomenclaturevehicle',
            name='tonnage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nomenclatures', to='mobility.Tonnage'),
        ),
        migrations.AddField(
            model_name='nomenclaturevehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nomenclatures', to='mobility.Type'),
        ),
        migrations.CreateModel(
            name='InsuranceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_status', models.CharField(max_length=150)),
                ('mv_file', models.FileField(upload_to=utils.PathAndRename('uploads/mobility/%Y/%m/'))),
                ('date_insured', models.DateField()),
                ('action', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commons.Unit')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance_schedules', to='mobility.VehicleRecord')),
            ],
            options={
                'verbose_name': 'Insurance Schedule',
                'verbose_name_plural': 'Insurance Schedules',
            },
        ),
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=512)),
                ('chasis_number', models.CharField(max_length=512)),
                ('plate_number', models.CharField(max_length=32)),
                ('cognizant_depot', models.CharField(max_length=512)),
                ('remarks', models.TextField()),
                ('action', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disposal_records', to='mobility.VehicleRecord')),
            ],
            options={
                'verbose_name': 'Disposal Records',
                'verbose_name_plural': 'Disposal Records',
            },
        ),
    ]
