# Generated by Django 2.2.3 on 2020-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerecord',
            name='nomenclature',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='vehiclerecord',
            name='serial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclerecord',
            name='serviceability',
            field=models.CharField(max_length=512),
        ),
    ]
