# Generated by Django 2.2.3 on 2021-09-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterOfTroops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('first_name', models.CharField(max_length=512)),
                ('middle_name', models.CharField(max_length=512)),
                ('serial_number', models.CharField(max_length=512)),
                ('unit', models.CharField(max_length=512)),
                ('title_position', models.CharField(max_length=512)),
                ('branch', models.CharField(max_length=512)),
                ('type_of_employment', models.CharField(max_length=512)),
                ('soi', models.FileField(upload_to=utils.PathAndRename('uploads/admin/%Y/%m/'))),
                ('phs', models.FileField(upload_to=utils.PathAndRename('uploads/admin/%Y/%m/'))),
                ('saln', models.FileField(upload_to=utils.PathAndRename('uploads/admin/%Y/%m/'))),
                ('per', models.FileField(upload_to=utils.PathAndRename('uploads/admin/%Y/%m/'))),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roster of Troops',
                'verbose_name_plural': 'Roster of Troops',
            },
        ),
        migrations.CreateModel(
            name='OutgoingCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commo_type', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('control_number', models.CharField(max_length=512)),
                ('origin_branch_office_unit', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('recepient_unit', models.CharField(max_length=512)),
                ('date_received', models.DateTimeField()),
                ('remarks', models.CharField(max_length=512)),
                ('received_by', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/admin/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outgoing Communication',
            },
        ),
        migrations.CreateModel(
            name='IncomingCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_branch', models.CharField(max_length=512)),
                ('commo_type', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=512)),
                ('control_number', models.CharField(max_length=512)),
                ('date_received', models.DateTimeField()),
                ('unit_office', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('remarks', models.CharField(max_length=512)),
                ('received_by', models.CharField(max_length=512)),
                ('action', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/admin/%Y/%m/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Communication',
            },
        ),
        migrations.CreateModel(
            name='AdminMooe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=512)),
                ('asa_number', models.CharField(max_length=512)),
                ('title_of_document', models.CharField(max_length=512)),
                ('quarter', models.CharField(max_length=512)),
                ('status', models.CharField(max_length=512)),
                ('year', models.IntegerField()),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/admin/%Y/%m/'))),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MOOE',
                'verbose_name_plural': 'MOOE',
            },
        ),
        migrations.CreateModel(
            name='AdminEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=512)),
                ('type_of_equipment', models.CharField(max_length=512)),
                ('modal_name', models.CharField(max_length=512)),
                ('purpose', models.CharField(max_length=512)),
                ('file_attachment', models.FileField(upload_to=utils.PathAndRename('uploads/admin/%Y/%m/'))),
                ('action', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
            },
        ),
    ]
